name: Deploy to Production (Docker Hub)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Jenkins Build
        uses: appleboy/jenkins-action@master
        with:
          url: "http://your-jenkins-url"
          user: "your-jenkins-username"
          password: "your-jenkins-api-token"
          job: "mlops-heart-disease-api"