name: Unit Testing
on:
  pull_request:
    branches: [ test ]
  push:
    branches: [ test ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt pytest
      
      - name: Run unit tests
        run: pytest tests/ -v --tb=short
      
      - name: Test API manually
        run: |
          python app/app.py &
          sleep 5
          curl -f http://localhost:5000/ || exit 1
          pkill -f "python app/app.py"